import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
return (
<>
    <Head>
		<title>Rowdy LA</title>
		<meta name="description" content="Generated by create next app" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
		<div className= 'center-board'>
		<h1>ROWDY LA IMAGE</h1>
			<div className='home-links'></div>
				<Link style={{textDecoration: 'none', color: 'white'}} href='/Shop'><p>Shop</p></Link>
				<p>About</p>
				<p></p>
			</div>
    </main>
</>
)
}

